name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest  # El servidor de test (Ubuntu)
    strategy:
      max-parallel: 4
      matrix:
        # Requisito: Ejecutar en estas 3 versiones de Python
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
      # Descarga tu código en el servidor de test

    - name: Set up Python ${{ matrix.python-version }}
      # Instala la versión de Python de la matriz
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install OS Dependencies (Firefox Headless)
      # ¡PUNTO CLAVE!
      # Requisito "headless": Tus tests piden Firefox.
      # El servidor 'ubuntu-latest' no lo trae.
      # Este paso instala Firefox y su driver (geckodriver).
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox-esr geckodriver

    - name: Install Python Dependencies
      # Instala las dependencias de tu proyecto
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      # ¡PUNTO CLAVE!
      # Ejecuta los tests de Selenium que creamos.
      # Tus tests ya están en modo "headless" (opts.add_argument).
      run: |
        python manage.py test polls
